import openURL from "open"; // helper to open a url in the default browser
import { exec } from "node:child_process";
// import { connect } from "./superdirt.mjs";

// helper to send messages to superdirt (expects sclang to run with tidal config)
// const dirt = connect();
// helper to run a terminal command
const cmd = (command) => {
  exec(command, (error, stdout, stderr) => {
    if (error) {
      console.error(`Error: ${error.message}`);
      return;
    }
    if (stderr) {
      console.error(`stderr: ${stderr}`);
      return;
    }
    console.log(stdout);
  });
};

// prequisite:
// 1. Google Chrome needs to be the default Browser
// 2. Terminal needs the rights to control keyboard input
// just enter
// osascript -e 'tell application "System Events" to keystroke return using control down'
// into the vscode terminal and you should get a prompt...
// 3. make sure to set SuperCollider Shortcut "Evaluate File" to ctrl+enter

const ctrlEnter = () => {
  cmd(
    `osascript -e 'tell application "System Events" to keystroke return using control down'`
  );
};

const killall = () => {
  cmd('killall "Google Chrome"');
  cmd('killall "SuperCollider"');
};

const sc = async (n) => {
  killall();
  await sleep(200);
  cmd(`SuperCollider ./sc/sc${n}.sc`);
  await sleep(5000);
  ctrlEnter();
};

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

const open = async (url) => {
  killall();
  await sleep(500);
  openURL(url);
  await sleep(2000);
  ctrlEnter();
};

const actions = {
  killall: () => killall(),
  // st actions will only work if SuperCollder is in PATH!
  sc1: () => sc(1),
  sc2: () => sc(2),
  sc3: () => sc(3),
  sc4: () => sc(4),
  sc5: () => sc(5),
  sc6: () => sc(6),
  sc7: () => sc(7),
  sc8: () => sc(8),
  sc9: () => sc(9),
  // using long urls instead of short ones, we can skip loading the code from the database..
  st1: () =>
    open(
      // "https://strudel.tidalcycles.org/?bihydW4oOCkucGFsaW5kcm9tZSgpKQouY2hvcmQoIjxEbTdbRzcgQTddPiIpCi52b2ljaW5nKCkgIC5zKCJzaW5lIikKLmFkZC5zcXVlZXplKG4oIjAgLjI1IgopKS5yb29tKDEpLmNsaXAoY29zaW5lCi5yYW5nZSguMSwyKSAuc2xvdyg0KSkKLmVjaG9XaXRoKDQsLjEsKHgsbik9Pgp4IC5hZGQobm90ZShuICogLjI1KSkpCi5zbG93KDQpLnB1bmNoY2FyZCh7fSk%3D#bihydW4oOCkucGFsaW5kcm9tZSgpKQouY2hvcmQoIjxEbTdbRzcgQTddPiIpCi52b2ljaW5nKCkgIC5zKCJzaW5lIikKLmFkZC5zcXVlZXplKG4oIjAgLjI1IgopKS5yb29tKDEpLmNsaXAoY29zaW5lCi5yYW5nZSguMSwyKSAuc2xvdyg0KSkKLmVjaG9XaXRoKDQsLjEsKHgsbik9Pgp4IC5hZGQobm90ZShuICogLjI1KSkpCi5zbG93KDQpLnB1bmNoY2FyZCh7fSk%3D" // ohne visual
      "https://strudel.tidalcycles.org/?bihydW4oOCkucGFsaW5kcm9tZSgpKQouY2hvcmQoIjxEbTdbRzcgQTddPiIpCi52b2ljaW5nKCkgIC5zKCJzaW5lIikKLmFkZC5zcXVlZXplKG4oIjAgLjI1IgopKS5yb29tKDEpLmNsaXAoY29zaW5lCi5yYW5nZSguMSwyKSAuc2xvdyg0KSkKLmVjaG9XaXRoKDQsLjEsKHgsbik9Pgp4IC5hZGQobm90ZShuICogLjI1KSkpCi5zbG93KDQpLnB1bmNoY2FyZCh7fSk%3D#bihydW4oOCkucGFsaW5kcm9tZSgpKQouY2hvcmQoIjxEbTdbRzcgQTddPiIpCi52b2ljaW5nKCkgIC5zKCJzaW5lIikKLmFkZC5zcXVlZXplKG4oIjAgLjI1IgopKS5yb29tKDEpLmNsaXAoY29zaW5lCi5yYW5nZSguMSwyKSAuc2xvdyg0KSkKLmVjaG9XaXRoKDQsLjEsKHgsbik9Pgp4IC5hZGQobm90ZShuICogLjI1KSkpCi5zbG93KDQpIC8vCgoKCgoKCgoKCgoKCiAgCgoKCgoKCgoKCi8vIHZpc3VhbAoudGhlbWUoJ3NvbGFyaXplZExpZ2h0JykuZm9udEZhbWlseSgnQmlnQmx1ZVRlcm1pbmFsJykKLmNvbG9yKCdwaW5rJykucGlhbm9yb2xsKHt2ZXJ0aWNhbDoxLGZvbGQ6MCxtaW5NaWRpOjUwfSk%3D"
    ),

  st2: () =>
    open(
      //"https://strudel.tidalcycles.org/#cygiYmQgcmltLCBbfiBoaCoyXSIpCi5iYW5rKCAiUm9sYW5kVFI5MDkiKQouZml0KCkuanV4KHJldikuY2h1bmsKKDQsIG11bCggc3BlZWQoMC41KSkpCi5yZXN0YXJ0KGA8eEA3IHgoNSw4KQo%2BYCkuanV4KHggPT4geCAuZ2FpbigKcmFuZCkucmV2KCkpLnN0YWNrKHMoCiJzYXd0b290aCIpLmV1Y2xpZFJvdAooMyw4LDQpLmxwZig4MDApLmxwcSgKc2F3LnJhbmdlKDEsOSkpKS8vIGZy" // without visuals
      "https://strudel.tidalcycles.org/#cygiYmQgcmltLCBbfiBoaCoyXSIpCi5iYW5rKCAiUm9sYW5kVFI5MDkiKQouZml0KCkuanV4KHJldikuY2h1bmsKKDQsIG11bCggc3BlZWQoMC41KSkpCi5yZXN0YXJ0KGA8eEA3IHgoNSw4KQo%2BYCkuanV4KHggPT4geCAuZ2FpbigKcmFuZCkucmV2KCkpLnN0YWNrKHMoCiJzYXd0b290aCIpLmV1Y2xpZFJvdAooMyw4LDQpLmxwZig4MDApLmxwcSgKc2F3LnJhbmdlKDEsOSkpKS8vIGZyCgoKCgoKCgoKCgoKCgoKCgoKCgogIAovLyB2aXN1YWwgIAoudGhlbWUoJ3doaXRlc2NyZWVuJykuZm9udEZhbWlseSgnQmlnQmx1ZVRlcm1pbmFsJykKLmNvbG9yKCJjeWFuIG1hZ2VudGEgeWVsbG93IikKLnNwaXJhbCh7Y2FwOidyb3VuZCcsY29sb3JpemVJbmFjdGl2ZTp0cnVlLHRoaWNrbmVzczoyMDAsc2l6ZToyMjAsaW5zZXQ6LTMsc3RlYWR5Oi45fSk%3D"
    ),

  st3: () =>
    open(
      //"https://strudel.tidalcycles.org/#bihydW4oMTIpKS5jaG9yZCgiRCIpCi52b2ljaW5nKCkucygicGlhbm8iKQouYWRkKCAiPC0xIDAgMSAwPi80IikKLmp1eChyZXYpLmxwcSg0KS5scGYoCnNhdy5yYW5nZSgxMDAsNDAwMCkpLgpyYXJlbHkoYWRkKG5vdGUoMTIpKSkKLmFkZChub3RlKHBlcmxpbi5kaXYoCjIpKSkubGFzdE9mKDQscmV2KS8vLwouc3ViKG5vdGUoIjEyWzAgMl0iKSkKLnNsb3coMikgIC5yb29tKHNpbmUpCi5waWFub3JvbGwoe2ZvbGQ6MSB9KQ%3D%3D" // ohne visual
      "https://strudel.tidalcycles.org/#bihydW4oMTIpKS5jaG9yZCgiRCIpCi52b2ljaW5nKCkucygicGlhbm8iKQouYWRkKCAiPC0xIDAgMSAwPi80IikKLmp1eChyZXYpLmxwcSg0KS5scGYoCnNhdy5yYW5nZSgxMDAsNDAwMCkpLgpyYXJlbHkoYWRkKG5vdGUoMTIpKSkKLmFkZChub3RlKHBlcmxpbi5kaXYoCjIpKSkubGFzdE9mKDQscmV2KS8vLwouc3ViKG5vdGUoIjEyWzAgMl0iKSkKLnNsb3coMikgIC5yb29tKHNpbmUpCgoKCgoKCiAgCgoKCgoKCgoKCgoKCiAgCiAgLy8gdmlzdWFsCiAgLnRoZW1lKCdub2N0aXNMaWxhYycpLmZvbnRGYW1pbHkoJ0JpZ0JsdWVUZXJtaW5hbCcpCiAgLmNvbG9yKCdvcmFuZ2UnKQogIC5zcGlyYWwoe2ZvbGQ6MSx0aGlja25lc3M6MTAsY2FwOidyb3VuZCcsY29sb3JpemVJbmFjdGl2ZToxLHN0ZWFkeTouOCB9KQ%3D%3D"
    ),
  st4: () =>
    open(
      //"https://strudel.tidalcycles.org/#bGV0IGNob3JkcyA9Y2hvcmQoYDwKQ143IEZeNyBFYl43IEFiXjc%2BYCkKc3RhY2sobihydW4oMTIpLnNsb3cKKDIpKS5qdXgoeD0%2BeC5yZXYoKS4KbGF0ZSguNSkpLnNldChjaG9yZHMKKS5vZmZzZXQoYDwwIDEgMiAxIDAgCi0xIC0yIC0xPi8yYC5hZGQoMSkpCi52b2ljaW5nKCkuY2xpcCgiMiIpCi5kZWxheSguNSkuZ2FpbihzaW5lCi5yYW5nZSguMiwxKS5mYXN0KC45CikpLGNob3Jkcy5yb290Tm90ZXMoCjIpKS5waWFubygpLmFkZChub3RlCihwZXJsaW4ucmFuZ2UoMCwuMjUpCikpLnB1bmNoY2FyZCgpIC8vIDwz" // ohne visual
      "https://strudel.tidalcycles.org/#bGV0IGNob3JkcyA9Y2hvcmQoYDwKQ143IEZeNyBFYl43IEFiXjc%2BYCkKc3RhY2sobihydW4oMTIpLnNsb3cKKDIpKS5qdXgoeD0%2BeC5yZXYoKS4KbGF0ZSguNSkpLnNldChjaG9yZHMKKS5vZmZzZXQoYDwwIDEgMiAxIDAgCi0xIC0yIC0xPi8yYC5hZGQoMSkpCi52b2ljaW5nKCkuY2xpcCgiMiIpCi5kZWxheSguNSkuZ2FpbihzaW5lCi5yYW5nZSguMiwxKS5mYXN0KC45CikpLGNob3Jkcy5yb290Tm90ZXMoCjIpKS5waWFubygpLmFkZChub3RlCihwZXJsaW4ucmFuZ2UoMCwuMjUpCikpLnB1bmNoY2FyZCgpIC8vIDwzCgoKCgoKCgoKCgoKCgoKCgoKICAKLy8gdmlzdWFsCi50aGVtZSgnYmx1ZXNjcmVlbicpCi5mb250RmFtaWx5KCdCaWdCbHVlVGVybWluYWwnKQouY29sb3IoJ3doaXRlJykKLnB1bmNoY2FyZCgp"
    ),
  hd1: () => open("https://hydra.ojack.xyz/?sketch_id=Pr16zeXkfaLUd5Kd"),
  hd2: () => open("https://hydra.ojack.xyz/?sketch_id=ExeOTZVE9hrn6IIW"),
  hd3: () => open("https://hydra.ojack.xyz/?sketch_id=vcWMV3vi1ykmd9U1"),
  hd4: () => open("https://hydra.ojack.xyz/?sketch_id=rhKdR4tUnVqL9gzX"),
  // extra content...
  st1x: () =>
    open(
      "https://strudel.tidalcycles.org/?bihydW4oOCkucGFsaW5kcm9tZSgpKQouY2hvcmQoIjxEbTdbRzcgQTddPiIpCi52b2ljaW5nKCkgIC5zKCJzaW5lIikKLmFkZC5zcXVlZXplKG4oIjAgLjI1IgopKS5yb29tKDEpLmNsaXAoY29zaW5lCi5yYW5nZSguMSwyKSAuc2xvdyg0KSkKLmVjaG9XaXRoKDQsLjEsKHgsbik9Pgp4IC5hZGQobm90ZShuICogLjI1KSkpCi5zbG93KDQpLnB1bmNoY2FyZCh7fSk%3D#bihydW4oOCkucGFsaW5kcm9tZSgpKSAvLyBydW4gOCB1cCBhbmQgZG93bgogIC5jaG9yZCgiPERtNyBbRzcgQTddPiIpIC8vIGNob3JkcwogIC52b2ljaW5nKCkgLy8gY2FsY3VsYXRlIG5vdGVzCiAgLnMoInNpbmUiKSAvLyBzb3VuZAogIC5wbHkoMikKICAuY2xpcChjb3NpbmUucmFuZ2UoLjEsMikuc2xvdyg4KSkgLy8gYXV0b21hdGUgbm90ZSBsZW5ndGgKICAuZWNob1dpdGgoNCwuMSwoeCxuKT0%2BeC5hZGQobm90ZShuLzQpKSkgLy8gcmVwZWF0IGFuZCBwaXRjaCB1cAogIC5zbG93KDQpIC8vIHNsb3cgaXQgZG93biAKICAucm9vbSgxKSAvLyByZXZlcmIKICAucHVuY2hjYXJkKHtmb2xkOjAsbWluTWlkaTo0MH0p"
    ),
  //st1: () => open("https://strudel.tidalcycles.org/?7VoIcReDMO-M"),
  st2sx: () =>
    open(
      "https://strudel.tidalcycles.org/#Ly8gdHJ5IHVzaW5nIGFub3RoZXIgZHJ1bSBtYWNoaW5lOiB0cnkgUm9sYW5kVFI4MDgsIEJvc3NEUjU1MCwgTVBDMTAwMAovLyB0cnkgdXNpbmcgYW5vdGhlciBzeW50aDogc3F1YXJlLCBnbV90dWJhLCBnbV9ndW5zaG90Ci8vIHRyeSBjaGFuZ2luZyBzb21lIG51bWJlcnMKCgpzKCJiZCByaW0sIFt%2BIGhoKjJdIikgLy8gcmh5dGhtOiBiYXNzZHJ1bSAoYmQpIHJpbXNob3QgKHJpbSksIGhpaGF0IChoaCkKICAuYmFuaygiUm9sYW5kVFI5MDkiKSAvLyB1c2UgUm9sYW5kVFI5MDkgYXMgZHJ1bSBtYWNoaW5lCiAgLmZpdCgpIC8vIHJlcGl0Y2ggZWFjaCBzb3VuZCB0byBleGFjdGx5IGZpdCBpdHMgc3BhY2UKICAuanV4KHJldikgLy8gcGxheSByZXZlcnNlZCB2ZXJzaW9uIGluIG90aGVyIHNwZWFrZXIKICAvLy5jaHVuayg0LCBtdWwoc3BlZWQoIjAuNSIpKSkgLy8gcGl0Y2ggZG93biBjaHVua3Mgb25lIGFmdGVyIHRoZSBvdGhlcgogIC5yZXN0YXJ0KGA8eEA3IHgoNSw4KT5gKSAvLyBwbGF5IGZpbGwgcmh5dGhtIGV2ZXJ5IDggYmFycwogIC5qdXgoeCA9PiB4LmdhaW4ocmFuZCkpIC8vIGFub3RoZXIgc3RlcmVvIGVmZmVjdAogIC5zdGFjayggLy8gYWRkIGFub3RoZXIgcGFydCBvbnRvcAogICAgcygic2F3dG9vdGgiKSAvLyB1c2Ugc2F3dG9vdGggd2F2ZQogICAgLmV1Y2xpZFJvdCgzLDgsNCkgLy8gYXBwbHkgYSByaHl0aG0KICAgIC5scGYoODAwKSAvLyBmaWx0ZXIgYXQgODAwSHoKICAgIC5scHEoc2F3LnJhbmdlKDEsOSkpIC8vIGF1dG9tYXRlIHJlc29uYW5jZQogICk%3D"
    ),
  // st2: () => open("https://strudel.tidalcycles.org/?dDsZmIqDmCXf"),
  st3x: () =>
    open(
      "https://strudel.tidalcycles.org/#bihydW4oMTIpKSAvLyBub3RlIGFycGVnZ2lvIG9mCiAgLmNob3JkKCJEIikgLy8gd2hpY2ggY2hvcmQKICAudm9pY2luZygpIC8vIGNhbGN1bGF0ZSBub3RlcyEKICAucygicGlhbm8iKSAvLyBzZXQgaW5zdHJ1bWVudAogIC5hZGQoICI8LTEgMCAxIDA%2BLzQiKSAvLyB0cmFuc3Bvc2UgZXZlcnkgNCBiYXJzCiAgLmp1eChyZXYpIC8vIHN0ZXJlbyByZXZlcnNlIGVmZmVjdAogIC5scGYoc2F3LnJhbmdlKDEwMCw0MDAwKSkgLy8gYXV0b21hdGVkIGZpbHRlcgogIC5scHEoNCkgLy8gZmlsdGVyIHJlc29uYW5jZQogIC5yYXJlbHkoYWRkKG5vdGUoIjEyIikpKSAvLyByYW5kb20gb2N0YXZlIGp1bXBzCiAgLmFkZChub3RlKHBlcmxpbi5kaXYoMikpKSAvLyBwaXRjaCB3YXJibGUKICAubGFzdE9mKDQsIHJldikgLy8gcmV2ZXJzZSBldmVyeSA0dGggY3ljbGUKICAuc3ViKG5vdGUoIjEyIFswIDJdIikpIC8vIHRyYW5zcG9zZSBkb3duIGJ5Li4KICAuc2xvdygyKSAvLyBzbG93IGV2ZXJ5dGhpbmcgZG93bgogIC5yb29tKHNpbmUpIC8vIGF1dG9tYXRlIHJldmVyYgogIC5waWFub3JvbGwoeyBmb2xkOjEgfSkgLy8gdmlzdWFsaXplIG5vdGVz"
    ),
  //st3: () => open("https://strudel.tidalcycles.org/?kl_UEvr3rc07"),
  st4x: () =>
    open(
      "https://strudel.tidalcycles.org/#Ly8gY2hhbmdlIGEgbnVtYmVyIGFuZCBjbGljayB1cGRhdGUhIGNhbiB5b3UgaGVhciB0aGUgZGlmZmVyZW5jZT8KLy8gdHJ5IGFkZGluZyAvLyBiZWZvcmUgYSBsaW5lIHRoYXQgc3RhcnRzIHdpdGggYSBkb3QsIHRoZW4gcHJlc3MgdXBkYXRlCgpsZXQgY2hvcmRzID0gY2hvcmQoYDxDXjcgRl43IEViXjcgQWJeNz5gKQovL2xldCBjaG9yZHMgPSBjaG9yZChgPENtNyBGbTcgRWJtNyBBYm03PmApIC8vIG1pbm9yIHZlcnNpb24KCnN0YWNrKCAvLyBjb21iaW5lIG11bHRpcGxlIHBhcnRzCiAgLy8gcGFydCAxOiBjaG9yZCBhcnBlZ2dpb3MKICBuKHJ1bigxMikuc2xvdygyKSkgLy8gYXJwZWdnaWF0ZSAocnVuIHVwKSBub3RlcwogIC5qdXgoeD0%2BeC5yZXYoKS5sYXRlKC41KSkgLy8gY29weSBhbmQgbW9kaWZ5IGluIHJpZ2h0IHNwZWFrZXIKICAuc2V0KGNob3JkcykgLy8gdXNlIGNob3JkcyBhYm92ZQogIC5vZmZzZXQoYDwxIDIgMyAyIDEgMCAtMSAwPi8yYCkgLy8gc2hpZnRzIHVwIC8gZG93bgogIC52b2ljaW5nKCkgLy8gY2FsY3VsYXRlIG5vdGVzCiAgLmNsaXAoMikgLy8gY29udHJvbHMgbm90ZSBsZW5ndGgKICAuZGVsYXkoLjUpIC8vIGFkZCBkZWxheSBlZmZlY3QKICAuZ2FpbihzaW5lLnJhbmdlKC4yLDEpLmZhc3QoLjkpKSAvLyB2YXJ5IHZvbHVtZQogICwKICAvLyBwYXJ0IDI6IGJhc3MKICBjaG9yZHMucm9vdE5vdGVzKDIpIC8vIHBsYXkgYmFzcyBub3RlcyBmb3IgZWFjaCBjaG9yZAopIAogIC8vIHRoZSBmb2xsb3dpbmcgaXMgYXBwbGllZCBmb3IgYm90aCBwYXJ0cwogIC5waWFubygpIC8vIHVzZSBwaWFubyBpbnN0cnVtZW50CiAgLmFkZChub3RlKHBlcmxpbi5yYW5nZSgwLC4yNSkpKSAvLyB3YXJibGUgbm90ZXMKICAucHVuY2hjYXJkKCkgLy8gZGlzcGxheSBub3RlcyAK"
    ),
  //st4: () => open("https://strudel.tidalcycles.org/?VUbgKpHsf-G9"),
  st5: () =>
    open(
      "https://felixroos.github.io/strudel/#Ly8gdGl0bGU6IHJlbGllZnBmZWlsZXIKcygiPHBlcmMgbWlzYyByaW0oMyw4KSBvaD4iKS5iYW5rKCdZYW1haGFURzMzJykuZW5kKCI8MUAzIC4wMj4iKQoubigiPDAgMSAyIDM%2BIi5vdXRzaWRlKDQsIHBhbGluZHJvbWUpKQoub2ZmKCI8MSAyIDMgND4iLmRpdigiPDIgMyA0IDY%2BLzQiKSwgeD0%2BeC5zcGVlZCgiPDIgMyA0PiIpKQogIAouY2h1bmsoNCwgcGx5KCI8MiAzIDQ%2BIikpCi5sYXN0T2YoOCwgc2VnbWVudCgiPDMgNiA4PiIpKQogIAoubGF5ZXIoCiAgeD0%2BeC5jdXRvZmYocGVybGluLnJhbmdlKDEwMDAsMjAwMDApKSwKICB4PT54LmJhbmsoJycpLnNsb3coMikucygncGlhbm8nKS5nYWluKC42KS5kZWdyYWRlKCkubXVsKHNwZWVkKC0xKSkKICAgIC5iYW5kZihzaW5lLnJhbmdlKDIwMDAsMTAwMDApLnNsb3coNykpLnJlc29uYW5jZSgxMikuYXR0YWNrKC44KQogICAgLnBhbihyYW5kKSwKKQogIAoubGFzdE9mKDYsIHg9PnguY3J1c2goIjgiKSkKLmdhaW4oc2F3LnJhbmdlKC40LC45KSkKLm91dHNpZGUoNCwganV4QnkoLjUsIHJldikpCi5ub3RlKCIwIDUgNCBbMiw3XSIuc2NhbGUoJ0cxIG1pbm9yJykpCi5yb29tKC40KS5mYXN0KDIvMykKLmNvbG9yKCJ0b21hdG8iKQoudGhlbWUoJ2JsYWNrc2NyZWVuJykuZm9udEZhbWlseSgnbW9ub3NwYWNlJykKLnNwaXJhbCh7CiAgY2FwOididXR0JywKICB0aGlja25lc3M6MjAsc3RyZXRjaDouNSwKICBzdGVhZHk6MC4wNSwKICBzaXplOjE1MCwKICBjb2xvcml6ZUluYWN0aXZlOjAsCiAgZmFkZToxLAogIGluc2V0OjAKfSkK"
    ),
  st6: () =>
    open(
      "https://strudel.tidalcycles.org/?C31_NrcMfZEO#Y29uc3Qge2lubmVyV2lkdGg6d3csaW5uZXJIZWlnaHQ6d2h9ID0gd2luZG93Owpjb25zdCBjdHggPSBnZXREcmF3Q29udGV4dCgpCmNvbnN0IHBpRGl2MTgwID0gTWF0aC5QSSAvIDE4MDsKZnVuY3Rpb24gZnJvbVBvbGFyKGFuZ2xlLCByYWRpdXMsIGN4LCBjeSkgewogIGNvbnN0IHJhZGlhbnMgPSAoYW5nbGUtOTApICogcGlEaXYxODAKICByZXR1cm4gW2N4ICsgTWF0aC5jb3MocmFkaWFucykgKiByYWRpdXMsIGN5ICsgTWF0aC5zaW4ocmFkaWFucykgKiByYWRpdXNdCn0KY29uc3QgW3csIGhdID0gWzIwMCwyMDBdCmNvbnN0IFtjeCxjeV0gPSBbd3cvMix3aC8yXTsKZnVuY3Rpb24gZHJhd1NwaXJhbFNlZ21lbnQoY3R4LCB7YSxiLHIsIGRlbnNpdHkgPSAyLCBjb2xvciA9ICdkYXJrc2VhZ3JlZW4nLCB0aGljayA9IDIsIGxvbmcgPSAxfSkgewogIGxldCBpID0gYTsKICBjdHguYmVnaW5QYXRoKCk7CiAgd2hpbGUoaSA8IGIpewogICAgY29uc3QgcmFkaXVzID0gTWF0aC5tYXgoTWF0aC5taW4ociAtIGkqLjIsMTAwMCksMjApOwogICAgY29uc3QgW3gxLHkxXSA9IGZyb21Qb2xhcihpLCByYWRpdXMsIGN4LCBjeSkKICAgIGNvbnN0IFt4Mix5Ml0gPSBmcm9tUG9sYXIoaSwgcmFkaXVzK2xvbmcsIGN4LCBjeSkKICAgIGN0eC5saW5lV2lkdGggPSB0aGljazsKICAgIGN0eC5tb3ZlVG8oeDEseTEpOwogICAgY3R4LnN0cm9rZVN0eWxlPSBjb2xvcgogICAgY3R4LmxpbmVUbyh4Mix5Mik7CiAgICBjdHguc3Ryb2tlKCkKICAgIGkrPTMwMC9kZW5zaXR5OwogIH0KfQpjb25zdCB7IHIsIGEsIGIsIGNvbG9yLCBkZW5zaXR5LHRoaWNrfSA9IAogIGNyZWF0ZVBhcmFtcygncicsICdhJywgJ2InLCAnY29sb3InLCdkZW5zaXR5JywndGhpY2snLCdsb25nJyk7CgoKY29uc3QgcGF0dGVybiA9IAogIHIoc2luZS5yYW5nZSgyMDAsODAwKS5zbG93KDQpKQogIC5hKGNvc2luZS5yYW5nZSgwLCA0NSkuc2xvdygzKSkKICAuYihwZXJsaW4ucmFuZ2UoMTAwMCwgNDAwMCkuc2xvdyg1KSkKICAudGhpY2soc2luZS5yYW5nZSgyLDUwKS5zbG93KDIpKQogIC5sb25nKHBlcmxpbi5yYW5nZSgxLDEwMCkuc2xvdygzKSkKICAub2ZmKDEsIHg9PnguY29sb3IoJ3doaXRlJykpCiAgLm9mZigyLCB4PT54LmNvbG9yKCdzYWxtb24nKSkKICAub2ZmKDQsIHg9PnguY29sb3IoJ3B1cnBsZScpKQogIC5zbG93KDQpLy8ubWFzaygieCg1LDgpIikKCgpmdW5jdGlvbiBvbkRyYXcoZikgeyAgCiAgY3R4LmJlZ2luUGF0aCgpOwogIGRyYXdTcGlyYWxTZWdtZW50KGN0eCwgZi52YWx1ZSk7Cn0KCgovLyBnZW5lcmljIGRyYXcgbG9naWMKd2luZG93LmZyYW1lICYmIGNhbmNlbEFuaW1hdGlvbkZyYW1lKHdpbmRvdy5mcmFtZSk7CgpmdW5jdGlvbiByZW5kZXIodCkgewogIHQgPSBNYXRoLnJvdW5kKHQpCiAgY29uc3QgZnJhbWUgPSBwYXR0ZXJuLnNsb3coMTAwMCkucXVlcnlBcmModCwgdCkKICBjdHguZmlsbFN0eWxlPScjMjAwMDEwMDUnCiAgY3R4LmZpbGxSZWN0KDAsMCx3dyx3aCkKICAvL2N0eC5jbGVhclJlY3QoMCwwLHd3LHdoKQogIGN0eC5zdHJva2UoKQogIGZyYW1lLmZvckVhY2gob25EcmF3KQogIHdpbmRvdy5mcmFtZSA9IHJlcXVlc3RBbmltYXRpb25GcmFtZShyZW5kZXIpOwp9OwoKd2luZG93LmZyYW1lID0gcmVxdWVzdEFuaW1hdGlvbkZyYW1lKHJlbmRlcik7CgoKCiIyIi5wb3cub3V0KCI8WzIsMTUsMzNdIFs3LDIwLDMzXSBbMTIsMjUsMzNdIFs3LDE1LDMzXT4iLmRpdigzMSkpLm11bCgxMTApLm11bChjYXQoMSwgOS84KS5zbG93KDgpKS5mcmVxKCkKICAubGF5ZXIoeD0%2BeC5hcnAoIjAgMSAyQDMwIi5sZWdhdG8oMzIpKSx4PT54Lm11bChmcmVxKDQpKS5sYXRlKDApLmFycCgiMCAxIDIgMSIuZmFzdCgxLjUpKS5sZWdhdG8oNCkpCi5waWFubygpLnNsb3coNCkucm9vbSguNSkudGhlbWUoJ2JsYWNrc2NyZWVuJykuZm9udEZhbWlseSgnbW9ub3NwYWNlJykKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCg%3D%3D"
    ),
  st7: () =>
    open(
      "https://felixroos.github.io/strudel/#Ly8gIlRlbGVwaG9uZSBPcGVyYXRvcnMgRHJlYW0gMSIKLy8gQGJ5IGZyb29zCgpyZWdpc3RlcignYWRkaXRpdmUnLCAodiwgcGF0KSA9PiB7CiAgdiA9IEFycmF5LmlzQXJyYXkodikgPyB2IDogW3ZdOwogIGNvbnN0IFsKICAgIHBhcnRpYWxzID0gOCwgLy8gbnVtYmVyIG9mIHBhcnRpYWxzCiAgICBhdHRhY2sgPSAuMDEsIC8vIHRpbWUgYmV0d2VlbiBlYWNoIHBhcnRpYWwKICAgIGRhbXAgPSAuNiwgIC8vIGRhbXBlbmluZyBwZXIgcGFydGlhbDogMl4oLW4qZGFtcCkKICAgIHNwcmVhZCA9IDEgLy8gcGFydGlhbCBzcHJlYWQgZmFjdG9yICgxPW5hdHVyYWwpCiAgXSA9IHY7CiAgcmV0dXJuIHBhdC5lY2hvV2l0aCgKICAgIHBhcnRpYWxzLAogICAgYXR0YWNrLAogICAgKHgsbik9PngKICAgICAgLm11bChmcmVxKG4rMSpzcHJlYWQpKQogICAgICAuZ2FpbihNYXRoLnBvdygyLCAtbipkYW1wKSkKICApCn0pCgoKIjU1IiAvLyA1NUh6ID0gQTIKLm11bC5taXgoIjwxIDQ6MygzLDgpPiIucmF0aW8oKSkgLy8gMSA9IGZ1bmRhbWVudGFsLCA0OjMgPSBqdXN0IGZvdXJ0aAouZnJlcSgpCi5zKCdzaW5lJykKLmFkZGl0aXZlKCI8MTYgOD4vOCAgICA6IDwuMDEgLjA1IC41IC45Pi82IDogLjMgOiAgICA8MSAxLjUgMiAzPi80IikKLy8gICAgICAgICAgXiBwYXJ0aWFscyAgICBeIGF0dGFjayAgICAgICAgICAgXiBkYW1wICAgXiBzcHJlYWQKLm11bChnYWluKC44KSkKLnBhbihyYW5kKQouY29sb3IoJ3RvbWF0bycpCi5waWFub3JvbGwoe3ZlcnRpY2FsOjEsZm9sZDowLHBsYXloZWFkQ29sb3I6J3RvbWF0bycscGxheWhlYWQ6Ljd9KQoudGhlbWUoJ2JsYWNrc2NyZWVuJykuZm9udEZhbWlseSgnbW9ub3NwYWNlJyk%3D"
    ),
  st8: () =>
    open(
      "https://strudel.tidalcycles.org/#Ly8gInRlbXBvdGFzY2hlbnR1Y2giIEBieSBmcm9vcwoKc2V0Y3BzKDEuNSkKCnN0YWNrKAogIHN0YWNrKAogICAgcygiYmQiKS5sYXN0T2YoMixsYXRlKDEvNCkpLmNvbG9yKCcjMDAxMTAwNTAnKQogICAgLAogICAgcygifiA8c2QgY3A%2BIikuY2xpcCguNSkuY29sb3IoJyNmZjAwMDAyMCcpLmNsaXAoLjI1KQogICAgLm1hc2soIjwwITE2IDEhMzI%2BIikKICAgIC5yb29tKCI8MCAuNT4iKS5jb2xvcigncGluaycpCiAgICAsCiAgICBzKCJoaCo8MiA0PiBbb2ggaGgqMl0iKQogICAgLm1hc2soIjwwITggMSEzMj4iKQogICAgLmNsaXAocGVybGluLnJhbmdlKC4xLC40KSkucmVsZWFzZSguMDUpCiAgICAuc3BlZWQoIlsxIC45XSozIikKICAgIC5nYWluKCJbLjYgLjJdKjIiKQogICAgLnJvb20oLjIpLmNvbG9yKCcjYWFmZmFhNTAnKSwKICApLmJhbmsoIlJvbGFuZFRSNzA3LFJvbGFuZFRSOTA5IikKICAubXVsKGdhaW4oLjYpKQogIC8vLmxwZihwZXJsaW4ucmFuZ2UoNTAwLDgwMDApLnNsb3coOCkpCiAgLAogIHN0YWNrKAogICAgbigiWzAgW34gMF0gMCo8MiAxPiAwP10vMiIpLmFkZCgiPDAhMiAzIDI%2BLzIiKS5zY2FsZSgiRzE6bWlub3IiKQogICAgLnMoInNhd3Rvb3RoIikubHBmKHBlcmxpbi5yYW5nZSgyMDAsMjAwMCkpLmxwcSg4KQogICAgLmFkZChub3RlKCIwLC4wMyIpKQogICAgLmRzKCIuMjowIikuY2xpcCguMykKICAgIC5jb2xvcignI2ZmYWEyMjUwJyksCiAgICAiPH4gW34gPEdtITcgRD5dPiIudm9pY2luZ3MoJ3RyaWFkcycpLm5vdGUoKQogICAgLnMoInNxdWFyZSIpCiAgICAuY3J1c2goOCkKICAgIC5jbGlwKHBlcmxpbi5yYW5nZSguMSwuMikpCiAgICAuZGVsYXkoLjUpLmxwZihwZXJsaW4ucmFuZ2UoODAwLDIwMDApKS5scHEoNCkKICAgIC5jb2xvcignI2ZmMDA0NDUwJykKICApCikKICAub3V0c2lkZSg0LGxhc3RPZig0LCB4PT54LmhwZig1MDApLnNwZWVkKDIpLmhwcSg0KSkpCiAgLnJlc2V0KCI8eEAxNSB4KDUsOCk%2BIikKICAuc2xvdygiPDEhNjQgMiEzMj4iKQogIC5mb250RmFtaWx5KCJnYWxhY3RpY28vMzIiKQogIC50aGVtZSgibm9yZC8zMiIpCiAgLnNwaXJhbCh7Y29sb3JpemVJbmFjdGl2ZTowLHRoaWNrbmVzczo4MCxzdGVhZHk6MS4wMn0pCg%3D%3D"
    ),
  st9: () =>
    open(
      "https://felixroos.github.io/strudel/#Ly8gdHJ5aW5nIG91dCBhbm90aGVyIHN0ZXZlIHJlaWNoIHRlY2huaXF1ZS4uCi8vIHZvY2FsIGZyb20gIkphY2sgS2Vyb3VhYyAtIEFtZXJpY2FuIEhhaWt1Igphd2FpdCBzYW1wbGVzKHsKICBkaWVkb2ZvbGRhZ2U6Jy4vZGllZG9mb2xkYWdlLm1wMycsCiAgbWVkaWNpbmVjYWJpbmV0OiAnLi9tZWRpY2luZWNhYmluZXQubXAzJywKfSwnZ2l0aHViOmZlbGl4cm9vcy9zYW1wbGVzL21haW4vdm9jYWxzLycpCgphcnJhbmdlKAogIFsxMCwgcygibWVkaWNpbmVjYWJpbmV0LzUiKV0sIAogIFsyMDUsIHMoImRpZWRvZm9sZGFnZSIpLmxheWVyKAogICAgeD0%2BeC5sb29wQXQoMS40KS5wYW4oMCkuY29sb3IoJyNmZjAwZWU1MCcpLAogICAgeD0%2BeC5sb29wQXQoMS4zOSkucGFuKDEpLmNvbG9yKCcjMDBlZWZmNTAnKSwKICApXQopLnBpYW5vcm9sbCh7Zm9sZDoxLHZlcnRpY2FsOjF9KQoudGhlbWUoJ2JsYWNrc2NyZWVuJykuZm9udEZhbWlseSgnbW9ub3NwYWNlJyk%3D"
    ),
  st10: () =>
    open(
      "https://strudel.tidalcycles.org/#UGF0dGVybi5wcm90b3R5cGUubmVzdCA9IGZ1bmN0aW9uKG4sIGN5Y2xlcykgewogIG4gPSByZWlmeShuKQogIHJldHVybiB0aGlzLmVjaG8obiwgcHVyZShjeWNsZXMpLmRpdihuKSwgMSkKfQoKUGF0dGVybi5wcm90b3R5cGUuZGVlcGltcG9zZSA9IGZ1bmN0aW9uKGZ1bmMsIHRpbWVzKSB7CiAgaWYodGltZXM9PT0wKSByZXR1cm4gdGhpczsKICByZXR1cm4gdGhpcy5zdXBlcmltcG9zZSh4PT5mdW5jKHgpLmRlZXBpbXBvc2UoZnVuYywgdGltZXMtMSkpCn0KCmFuZ2xlKHNhdykKICAuZmlsbCgnI2FhZmZlZTEyJykKICAuciguMTgpCiAgLncoLjA2KQogIC5oKC4wNikKICAuZGVlcGltcG9zZSh4PT54Lm11bChyKDIpLncoMikuaCgyKSkubGF0ZSgxLzEyKSwgMykKICAubmVzdCg2LCAxKQogIC5zKCdlbGxpcHNlJykKICAubXVsKHcoc2luZSkuaChzaW5lKS5yYW5nZSguNSwxLjI1KSkKICAub2ZmKC41LCB4PT54LmZpbGwoJyNmZmVlYWExMicpLnJldigpLmRpdihyKDEuMikpKQogIC5zbG93KDE2KQogIC5zbWVhcigwLjYpCiAgLmFuaW1hdGUoe3NtZWFyOjB9KQoK"
    ),
};

let pending = null;
export const action = async (code) => {
  console.log("beep", code);
  if (pending) {
    console.log(`waiting for code "${code}" to finish...`);
    await pending;
    console.log(`code "${code}" finished!`);
  }
  // actions
  const action = actions[code];
  if (!action) {
    console.log(
      `code "${code}" is unknown.. just pretending nothing happened...`
    );
    return;
  }
  console.log(`running code "${code}"`);
  pending = action();
};
